baseURL = 'https://github.com/JRLapierre/JRLapierre.github.io/'
languageCode = 'fr-fr'
title = 'My New Hugo Site'
theme = 'iutdelens'
categories : ["Projet", "Développement web"]


[[menu.main]] 
  name = "À propos" 
  url = "/a-propos-de" 
 
[[menu.main]] 
  name = "Blog" 
  url = "/blog"

[[menu.footer]] 
  name = "À propos" 
  url = "/a-propos-de"

[[menu.social]] 
  name = "GitHub" 
  url = "https://github.com/VotreCompteGithub" 
  pre = "<i class='fab fa-github'></i>" 
 
 
[[menu.social]] 
  name = "Twitter" 
  url = "https://twitter.com/VotreCompteTwitter" 
  pre = "<i class='fab fa-twitter'></i>"

[params]
author = "Moi"
authorImage = "/images/stayCalm.png"

